function documentShell(title: string, body: string, styles: string, script = ''): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>${styles}</style></head><body>${body}${script ? `<script>${script}</script>` : ''}</body></html>`;
}

const palette = `
  :root{color-scheme:dark;--void:#05070d;--panel:#0b1020;--line:#22345c;--cyan:#52e7ff;--violet:#a879ff;--text:#e9f5ff;--muted:#88a2be;--good:#74f6a7}
  *{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 50% 0,#182857 0,var(--void) 48%);color:var(--text);font:14px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}
  a{color:inherit;text-decoration:none}.brand{letter-spacing:.22em;text-transform:uppercase}.pill{border:1px solid var(--line);border-radius:999px;padding:.35rem .7rem;color:var(--cyan)}
`;

export function planetarySurface(mode: string, umbrella: string, module: string): string {
  return documentShell(
    'Planetary-Max',
    `<header><div class="brand">Planetary-Max</div><a class="pill" href="/max-os-1">Open MAX-OS-1 console →</a></header>
    <main><section class="hero"><div class="orb"><span></span><span></span><span></span></div><p class="eyebrow">Portal-OS Worker / planetary substrate</p><h1>One surface.<br>Many universes.</h1><p class="lede">Persistent kernel services, governed evolution, and federated envelope routing converge in the Planetary-Max root.</p></section>
    <section class="grid"><article><small>WORKER</small><strong>Portal-OS Worker</strong><em>ONLINE</em></article><article><small>MODE</small><strong>${escapeHtml(mode)}</strong><em>COHERENT</em></article><article><small>UMBRELLA</small><strong>${escapeHtml(umbrella)}</strong><em>ENFORCED</em></article><article><small>MODULE</small><strong>${escapeHtml(module)}</strong><em>BOUND</em></article></section></main>`,
    `${palette}
    header{height:72px;padding:0 5vw;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line);background:#05070dcc}main{max-width:1200px;margin:auto;padding:8vh 5vw}.hero{min-height:52vh;position:relative;display:flex;flex-direction:column;justify-content:center}.eyebrow{color:var(--cyan);letter-spacing:.16em;text-transform:uppercase}.hero h1{font:700 clamp(3.5rem,9vw,8rem)/.88 system-ui;margin:.25em 0;letter-spacing:-.07em}.lede{max-width:650px;color:var(--muted);font:1.05rem/1.7 system-ui}.orb{position:absolute;right:4%;top:10%;width:310px;aspect-ratio:1;border:1px solid #52e7ff55;border-radius:50%;box-shadow:0 0 100px #525fff33,inset 0 0 80px #a879ff22;animation:float 8s ease-in-out infinite}.orb span{position:absolute;inset:15%;border:1px solid #a879ff88;border-radius:50%;transform:rotateX(65deg)}.orb span:nth-child(2){transform:rotateY(65deg)}.orb span:nth-child(3){inset:42%;background:var(--cyan);box-shadow:0 0 40px var(--cyan)}.grid{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--line)}article{min-height:150px;padding:1.4rem;border-right:1px solid var(--line);display:flex;flex-direction:column;gap:.7rem}article:last-child{border:0}small{color:var(--muted)}strong{font:1.1rem system-ui}em{margin-top:auto;color:var(--good);font-style:normal;font-size:.75rem}@keyframes float{50%{transform:translateY(20px) rotate(8deg)}}@media(max-width:800px){.orb{opacity:.25}.grid{grid-template-columns:1fr 1fr}article:nth-child(2){border-right:0}.hero h1{font-size:4rem}}`
  );
}

export function maxOsConsole(): string {
  return documentShell(
    'MAX-OS-1 console',
    `<header><a href="/" class="brand">Planetary-Max</a><div>MAX-OS-1 console <span class="status">● QUANTUM LINK</span></div></header>
    <main><aside class="panel navigation"><h2>SUBSYSTEMS</h2><label>Access token<input id="access-token" type="password" autocomplete="off" spellcheck="false"></label><nav>
    <button data-type="kernel.ping" data-payload="{}">◈ Kernel</button><button data-type="universe.state" data-payload="{}">◎ Universe</button><button data-type="universe.tick" data-payload='{"steps":1}'>↻ Tick</button><button data-type="universe.umbrella" data-payload="{}">⌁ Umbrella</button><button data-type="process.list" data-payload="{}">▤ Processes</button><button data-type="module.state" data-payload="{}">◇ Modules</button><button data-type="identity.inspect" data-payload="{}">◉ Identities</button><button data-type="cluster.state" data-payload="{}">✣ Federation</button></nav><div class="quantum"><i></i><i></i><i></i><span>Q-STATE<br><b id="qstate">COHERENT</b></span></div></aside>
    <section class="panel terminal"><div class="panel-title">TERMINAL <button id="clear">CLEAR</button></div><div id="terminal" aria-live="polite"><p class="system">Portal-OS Worker link established. Select a subsystem or enter an envelope operation.</p></div><form id="command"><span>max@planetary:~$</span><input id="operation" aria-label="Envelope operation" placeholder="kernel.ping {}" autocomplete="off" spellcheck="false"></form></section>
    <aside class="panel inspector"><div class="panel-title">INSPECTOR</div><dl><dt>ENVELOPE ID</dt><dd id="envelope-id">—</dd><dt>TYPE</dt><dd id="envelope-type">—</dd><dt>IDENTITY</dt><dd id="envelope-identity">—</dd><dt>LATENCY</dt><dd id="latency">—</dd></dl><div class="panel-title logs-title">LOGS</div><div id="logs"></div></aside></main>`,
    `${palette}
    body{height:100vh;overflow:hidden}header{height:54px;display:flex;align-items:center;justify-content:space-between;padding:0 18px;border-bottom:1px solid var(--line);background:#070b15}.status{color:var(--good);margin-left:1rem;font-size:.75rem}main{height:calc(100vh - 54px);display:grid;grid-template-columns:240px minmax(360px,1fr) 320px;gap:1px;background:var(--line)}.panel{background:linear-gradient(180deg,#0b1020,#070a13);min-width:0}.navigation{padding:18px;position:relative}.navigation h2,.panel-title{font-size:.75rem;letter-spacing:.15em;color:var(--muted);margin:0 0 1rem}.navigation label{display:block;color:var(--muted);font-size:.72rem}.navigation input{width:100%;margin:.4rem 0 1rem;background:#05070d;border:1px solid var(--line);color:var(--cyan);padding:.55rem}nav{display:grid;gap:6px}button{font:inherit;color:var(--text);background:#10182d;border:1px solid #26385f;padding:.65rem;text-align:left;cursor:pointer}button:hover{border-color:var(--cyan);color:var(--cyan)}.quantum{position:absolute;bottom:25px;width:200px;height:150px;display:grid;place-items:center}.quantum i{position:absolute;width:110px;height:110px;border:1px solid #52e7ff77;border-radius:50%;animation:spin 7s linear infinite}.quantum i:nth-child(2){transform:rotateX(65deg);animation-direction:reverse}.quantum i:nth-child(3){width:14px;height:14px;background:var(--violet);box-shadow:0 0 25px var(--violet)}.quantum span{text-align:center;font-size:.66rem;color:var(--muted)}.quantum b{color:var(--good)}.terminal{display:grid;grid-template-rows:42px 1fr 52px}.panel-title{padding:14px;margin:0;border-bottom:1px solid var(--line)}.panel-title button{float:right;padding:0;border:0;background:none;font-size:.7rem}#terminal{padding:18px;overflow:auto}#terminal p{margin:.4rem 0;white-space:pre-wrap;word-break:break-word}.system{color:var(--cyan)}.error{color:#ff6c8d}.command{color:var(--violet)}form{border-top:1px solid var(--line);display:flex;align-items:center;padding:0 14px;color:var(--good);gap:9px}form input{flex:1;min-width:0;background:transparent;border:0;outline:0;color:var(--text);font:inherit}.inspector{overflow:auto}.inspector dl{padding:0 16px}.inspector dt{font-size:.65rem;color:var(--muted);margin-top:1rem}.inspector dd{margin:.25rem 0;word-break:break-all;color:var(--cyan)}.logs-title{margin-top:1rem;border-top:1px solid var(--line)}#logs{padding:0 14px}#logs p{border-left:2px solid var(--violet);padding-left:9px;color:var(--muted);font-size:.72rem}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:900px){main{grid-template-columns:180px 1fr}.inspector{display:none}.quantum{width:140px}}@media(max-width:540px){body{overflow:auto}header{padding:0 10px;font-size:.7rem}.status{display:none}main{height:auto;min-height:calc(100vh - 54px);grid-template-columns:minmax(0,1fr)}.navigation{padding:10px 14px}.navigation h2,.navigation nav,.quantum{display:none}.navigation input{margin-bottom:0}.terminal{height:calc(100vh - 124px);min-height:420px}}`,
    `const terminal=document.querySelector('#terminal');const logs=document.querySelector('#logs');const accessToken=document.querySelector('#access-token');const print=(text,kind='')=>{const p=document.createElement('p');p.className=kind;p.textContent=text;terminal.append(p);terminal.scrollTop=terminal.scrollHeight};async function send(type,payload){const started=performance.now();document.querySelector('#qstate').textContent='COLLAPSING';print('> '+type+' '+JSON.stringify(payload),'command');try{const response=await fetch('/api/kernel/message',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+accessToken.value},body:JSON.stringify({type,payload,governanceContext:{surface:'MAX-OS-1 console',quantumState:'observed'}})});const result=await response.json();const elapsed=(performance.now()-started).toFixed(1)+' ms';document.querySelector('#envelope-id').textContent=result.envelope?.id||'—';document.querySelector('#envelope-type').textContent=result.envelope?.type||type;document.querySelector('#envelope-identity').textContent=result.envelope?.identity||'—';document.querySelector('#latency').textContent=elapsed;print(JSON.stringify(result,null,2),response.ok?'system':'error');const log=document.createElement('p');log.textContent=new Date().toLocaleTimeString()+' '+type+' ['+response.status+']';logs.prepend(log);while(logs.children.length>30)logs.lastElementChild.remove();document.querySelector('#qstate').textContent=response.ok?'COHERENT':'DECOHERENT'}catch(error){print(String(error),'error');document.querySelector('#qstate').textContent='DECOHERENT'}}document.querySelectorAll('[data-type]').forEach(button=>button.addEventListener('click',()=>send(button.dataset.type,JSON.parse(button.dataset.payload))));document.querySelector('#clear').addEventListener('click',()=>terminal.replaceChildren());document.querySelector('#command').addEventListener('submit',event=>{event.preventDefault();const input=document.querySelector('#operation');const value=input.value.trim();if(!value)return;const split=value.indexOf(' ');const type=split<0?value:value.slice(0,split);try{const payload=split<0?{}:JSON.parse(value.slice(split+1));if(!payload||Array.isArray(payload)||typeof payload!=='object')throw new Error('Payload must be an object');input.value='';send(type,payload)}catch(error){print('Invalid command: '+String(error),'error')}});`
  );
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] ?? character);
}
